name: Java and Gradle Job Setup
description: Sets up Java and Gradle
runs:
  using: "composite"
  steps:
    # Setup java
    - name: Setup JDK 17
      id: setup_jdk
      uses: actions/setup-java@v4.3.0
      with:
        distribution: "corretto"
        java-version: 17

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      id: grant_gradle_permission
      shell: bash
      run: chmod +x gradlew

    # Caching gradle packages
    - uses: actions/cache@v4
      name: Cache Gradle for quicker builds
      id: caching_gradle
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Setup Gradle
    - name: Set up Gradle
      id: set_up_gradle
      uses: gradle/actions/setup-gradle@v4