name: Java and Gradle Job Setup
description: Sets up Java and Gradle
runs:
  using: "composite"
  steps:
    # Setup java
    - name: Setup JDK 21
      id: setup_jdk
      uses: actions/setup-java@v5.0.0
      with:
        distribution: 'zulu'
        java-version: 21

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      id: grant_gradle_permission
      shell: bash
      run: chmod +x gradlew

    # Caching gradle packages
    # TODO: remove temporary workaround after fixed
    # temporarily work around https://github.com/actions/runner-images/issues/13341
    # by disabling caching for macOS
    - if: ${{ runner.os != 'macOS' }}
      uses: actions/cache@v4
      name: Cache Gradle for quicker builds
      id: caching_gradle
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Setup Gradle
    - name: Set up Gradle
      id: set_up_gradle
      uses: gradle/actions/setup-gradle@v4